config/routes.rb
Blog::Application.routes.draw do
	resources :posts

  

end

app/models/post.rb
class Post < ActiveRecord::Base

=begin
	validates :title, :content, :presence => true
	validates :title, :length => { :minimum => 2}
	validates :title, :uniqueness => true
=end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@posts = Post.all
	end
	
	def show
		@posted = Post.find(params[:id])#url'nin sonundaki id nolu postu gösterir.
	end
	
	def new
	#viewe boş bir post nesnesi göndermek için @post isminde bir instance variable tanımladık...
		@posts = Post.new		
		
	end
	
	def create
		@post = Post.new(params[:posts])
		@post.save
		if @post.save
			redirect_to posts_path, :notice => "Your post was saved"
		else
			render "new"
		end
	end
	
	def edit
		@post = Post.find(params[:id])
	end 
	
	def update
		@post = Post.find(params[:id])
		
		if @post.update_attributes(:id => params[:id])
			redirect_to posts_path, :notice => "Your post has been updated"
		
		else
			render "edit"
		end
	end
	
	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path, :notice => "Your post has been succesfully deleted "
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>
	<p><%= value %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	
	<p>
		<%= f.label :content %><br />
		<%= f.text_area :content %>
	</p>
	
	<p>
		<%= f.submit "Update Post" %>
	</p>
<%end%>

app/views/posts/index.html.erb
<h1> Our Blog </h1>

<% @posts.each do |post| %>
	<h2><%= link_to post.title, post %></h2>
	<p><%= post.content %></p>
	<p>
		<%= link_to "Edit", edit_post_path(post)%> |
		<%= link_to "Delete", post, :confirm => "Are you sure?", :method => :delete %>
	</p>
	<hr />
<% end %>

<p><%= link_to "Add a New Post",new_post_path %></p>

app/views/posts/new.html.erb
<h1>Add a New Post</h1>

<%= form_for @posts do |f| %>
<!--
	<% if @posts.errors.any? %>
		<h2>Errors:</h2>
		<ul>
			<% @posts.error.full_messages.each do |message| %>
				<li><%= messsage %></li>
			<%end%>
	<%end%>
	
		</ul>
		-->
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	
	<p>
		<%= f.label :content %><br />
		<%= f.text_area :content %>
	</p>
	
	<p>
		<%= f.submit "Add a New Post" %>
	</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @posted.title %></h1>
<p><%= @posted.content %></p>
<small> sent at <%= @posted.created_at%></small>